package Vista;

import Modelo.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Time;

/**
 *
 * @author Usuario
 */

public class JInternalFrameRevista extends javax.swing.JInternalFrame {

    public JInternalFrameRevista() {
        initComponents();
        jTextnumero.setEnabled(false);//Deshabilitar campo de numero
    }

      public void LimpiarCampos(){
        jTextnumero.setText("");
        jTexttitulo.setText("");
        jTextayo.setText("");
        jTextissn.setText("");
         jTextprecio.setText("");
         jTexthoraventa.setText("");
    }
      
      //Metodo para listar datos dentro de la tabla
    public void obtenerDatos(){
        //se crea una lista que almacena los datos obtenidps
        List<Revista> revistas=new DAORevista().ObtenerDatos();
        //Define un Modelo para la tabla
        DefaultTableModel modelo= new DefaultTableModel();
        //Arreglo con nombres de columnas de la tabla
        String[] columnas={"Numero","Titulo","año","Issn","Precio","Horaventa"};
        //Establece los nombres definidos de la columnah
        modelo.setColumnIdentifiers(columnas);
        for(Revista rev:revistas){ //Recorre cada elemento de la lista y los agrega
            //al modelo de la tabla
            String[]renglon={Integer.toString(rev.getNumero()), rev.getTitulo(),
                Integer.toString (rev.getAyo()), rev.getIssn(),  
                Float.toString(rev.getPrecio()),
                rev.getHoraventa().toString()};
                modelo.addRow(renglon);
         }
         jTableRevista.setModel(modelo);//Ubica los datos del modelo en la tabla
}
    public void actualizarRevista(){
        int num=Integer.parseInt(this.jTextnumero.getText());
         String titu=jTexttitulo.getText();
        int ay=Integer.parseInt(this.jTextayo.getText());
         String iss=jTextissn.getText();
        float pre=Float.parseFloat(this.jTextprecio.getText());
        Time hrv=Time.valueOf(this.jTexthoraventa.getText());
             
        DAORevista dao=new DAORevista();
        int res=dao.Actualizar(num, titu, ay, iss, pre ,hrv);
        if(res==1){
            JOptionPane.showMessageDialog(rootPane, "¡Revista actualizada!");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "¡Ocurrio un error!");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAutor = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextnumero = new javax.swing.JTextField();
        jTexthoraventa = new javax.swing.JTextField();
        jTexttitulo = new javax.swing.JTextField();
        jTextissn = new javax.swing.JTextField();
        jTextprecio = new javax.swing.JTextField();
        jTextayo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBAgregarR = new javax.swing.JButton();
        jBBorrarR = new javax.swing.JButton();
        jBEditarR = new javax.swing.JButton();
        jBActualizarR = new javax.swing.JButton();
        jBBuscarR = new javax.swing.JButton();
        jTextBuscarR = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRevista = new javax.swing.JTable();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Autores Registrados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel3.setLayout(new javax.swing.OverlayLayout(jPanel3));

        jTableAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTableAutor);

        jPanel3.add(jScrollPane1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar / Actualizar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Numero");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 54, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 177, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 137, -1, -1));

        jTextnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnumeroActionPerformed(evt);
            }
        });
        jPanel2.add(jTextnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 50, 200, -1));

        jTexthoraventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexthoraventaActionPerformed(evt);
            }
        });
        jPanel2.add(jTexthoraventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 200, -1));

        jTexttitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexttituloActionPerformed(evt);
            }
        });
        jPanel2.add(jTexttitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 90, 200, -1));
        jPanel2.add(jTextissn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 200, -1));

        jTextprecio.setText("0");
        jPanel2.add(jTextprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 200, -1));
        jPanel2.add(jTextayo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 200, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Titulo");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 94, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Ayo");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Issn");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Precio");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("HoraVenta");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transacciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        jBAgregarR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBAgregarR.setForeground(new java.awt.Color(0, 0, 102));
        jBAgregarR.setText("Agregar");
        jBAgregarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarRActionPerformed(evt);
            }
        });

        jBBorrarR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBBorrarR.setForeground(new java.awt.Color(0, 0, 102));
        jBBorrarR.setText("Borrar");
        jBBorrarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarRActionPerformed(evt);
            }
        });

        jBEditarR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBEditarR.setForeground(new java.awt.Color(0, 0, 102));
        jBEditarR.setText("Editar");
        jBEditarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarRActionPerformed(evt);
            }
        });

        jBActualizarR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBActualizarR.setForeground(new java.awt.Color(0, 0, 102));
        jBActualizarR.setText("Actualizar");
        jBActualizarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarRActionPerformed(evt);
            }
        });

        jBBuscarR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBBuscarR.setForeground(new java.awt.Color(0, 0, 102));
        jBBuscarR.setText("Buscar");
        jBBuscarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarRActionPerformed(evt);
            }
        });

        jTextBuscarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBuscarRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBEditarR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBActualizarR))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jBAgregarR)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jBBorrarR)
                                .addGap(62, 62, 62))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jTextBuscarR, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBBuscarR)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jBAgregarR)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBActualizarR)
                    .addComponent(jBEditarR))
                .addGap(28, 28, 28)
                .addComponent(jBBorrarR)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBBuscarR)
                    .addComponent(jTextBuscarR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, 250));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Revista/Registradas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel4.setLayout(new javax.swing.OverlayLayout(jPanel4));

        jTableRevista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(jTableRevista);

        jPanel4.add(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarRActionPerformed
        // Captura  datos de la caja de texto
        String titu=jTexttitulo.getText();
        int ay=Integer.parseInt(this.jTextayo.getText());
        String iss=jTextissn.getText();
        float pre=Float.parseFloat(this.jTextprecio.getText());
        String hrv=jTexthoraventa.getText();
        //Comprueba que las cajas  de texto no esten vacias
        if(titu.contentEquals("")||Integer.toString(ay).contentEquals("")||
            iss.contentEquals("")||Float.toString(pre).contentEquals("")||
                hrv.contentEquals("")){
            
            JOptionPane.showMessageDialog(rootPane,
                "Todos los campos son obligatorios");
        }else{
            
            try{
                 
               Time hrvTime = Time.valueOf(hrv); // Convierte el String a Time
               // Objeto para acceder al método Insertar de DAORevista
               Revista rev=new DAORevista().Insertar(titu, ay, iss, pre, hrvTime);
               JOptionPane.showMessageDialog(rootPane,"Registro agregado");

         }catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "No se agrego el registro");

            }
        }
        obtenerDatos(); //llama a este metodo para que se muestre el nuevo
        // registro en la tabla de formularios
        LimpiarCampos();

    }//GEN-LAST:event_jBAgregarRActionPerformed

    private void jBBorrarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarRActionPerformed
        int fila=this.jTableRevista.getSelectedRow();
        if(fila==1){
            JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
        }
        else{
            int num=Integer.parseInt((String)this.jTableRevista.getValueAt(fila, 0).toString());
            DAORevista dao=new DAORevista();
            dao.Eliminar(num);
            obtenerDatos();
        }

    }//GEN-LAST:event_jBBorrarRActionPerformed

    private void jBEditarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarRActionPerformed
        int fila=this.jTableRevista.getSelectedRow(); //Se obtiene filas seleccionadas
        // y se asigna a una variable
        if (fila==-1){
            JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
        }
        else{ //Se toma cada campo de la tabla del registro seleccionado
            // y se asigna una variable
            try{
                int id=Integer.parseInt((String)this.jTableRevista.getValueAt(fila, 0).toString());
                String titu=(String)this.jTableRevista.getValueAt(fila,1);
                String  ay=(String)this.jTableRevista.getValueAt(fila,2);
                String iss=(String)this.jTableRevista.getValueAt(fila,3);
                String pre=(String)this.jTableRevista.getValueAt(fila,4);
                Time hrv=Time.valueOf((String)this.jTableRevista.getValueAt(fila, 5).toString());

                //Se ubican en las cajas de textos los datos capturados de la tabla
                jTextnumero.setText(""+id);
                jTexttitulo.setText(titu);
                jTextayo.setText(ay);
                jTextissn.setText(iss);
                jTextprecio.setText(pre);
                jTexthoraventa.setText(String.valueOf(hrv));
            }catch(NumberFormatException e){
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_jBEditarRActionPerformed

    private void jBActualizarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarRActionPerformed
        actualizarRevista();
        obtenerDatos();
        LimpiarCampos();

    }//GEN-LAST:event_jBActualizarRActionPerformed

    private void jBBuscarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBuscarRActionPerformed

    private void jTextBuscarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBuscarRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBuscarRActionPerformed

    private void jTexttituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexttituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexttituloActionPerformed

    private void jTexthoraventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexthoraventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexthoraventaActionPerformed

    private void jTextnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnumeroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizarR;
    private javax.swing.JButton jBAgregarR;
    private javax.swing.JButton jBBorrarR;
    private javax.swing.JButton jBBuscarR;
    private javax.swing.JButton jBEditarR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAutor;
    private javax.swing.JTable jTableRevista;
    private javax.swing.JTextField jTextBuscarR;
    private javax.swing.JTextField jTextayo;
    private javax.swing.JTextField jTexthoraventa;
    private javax.swing.JTextField jTextissn;
    private javax.swing.JTextField jTextnumero;
    private javax.swing.JTextField jTextprecio;
    private javax.swing.JTextField jTexttitulo;
    // End of variables declaration//GEN-END:variables
}
